SUPABASE_URL="https://xsbbbjbvejeividiljlk.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzYmJiamJ2ZWplaXZpZGlsamxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyMjMwNDYsImV4cCI6MjEwMzc5OTA0Nn0.QJ_h7aLcBQxpYwnmolvA61KiDPSQpGrkjW3lbMU_uz8"